
services:
  sona-web:
    container_name: sona-web
    hostname: sona-web
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
